name: "Spheron Action"
description: "Upload a built folder to spheron network"
inputs:
  spheron-api-key:
    description: "spheron api key"
    required: true
    default: ""
  spheron-project-name:
    description: "spheron project name"
    required: true
    default: ""
  spheron-organization-id:
    description: "spheron organizition id"
    required: false
    default: ""
  spheron-upload-folder:
    description: "spheron upload folder name"
    required: true
    default: "build"
  spheron-protocol:
    description: "spheron protocol"
    required: true
    default: "ipfs-pinata"
outputs:
  site:
    description: "The url of the deployment on spheron network"
runs:
  using: "node16"
  main: "dist/index.js"
