name: 'Spheron Upload Action'
description: 'Upload a built folder to spheron network'
inputs:
  spheron-api-key:
    description: 'spheron api key'
    required: true
    default: ''
  spheron-project-name:
    description: 'spheron project name'
    required: true
    default: ''
  spheron-organization-id: 
    description: 'spheron organizition id'
    required: false
    default: ''
outputs:
  site:
    description: 'The url of the deployment on spheron network'
runs:
  using: 'node16'
  main: 'dist/index.js'
